Search Page small things
reidst/csci340-iseegreen pull request #25
Opened 2023-12-04 01:49 UTC by k-atej

Styling/minor fixes to the search page
- added descending sorting to genus & species
- set species sort to default
- styled table to be more readable
- added ability to clear filters 
- added column of checkboxes (not currently functional, but representative of "selecting" a plant)

*does not fix pagination/sort conflict bug

2023-12-04 22:15 UTC, k-atej commented
Fixed the Category/Search parameter conflict with pagination, as well as sort order conflict with pagination.

2023-12-04 23:32 UTC, reidst commented
There's still an issue sorting when trying to go from `genus_desc` to `genus`, but that can be fixed by changing Pages/Search/Index.cshtml.cs line 67 like this:
```diff
  public async Task OnGetAsync(...)
  {
-     GenusSort = String.IsNullOrEmpty(sortOrder)? "genus": "genus_desc";
+     GenusSort = (String.IsNullOrEmpty(sortOrder) || sortOrder.Equals("genus_desc"))? "genus": "genus_desc";
      SpeciesSort = String.IsNullOrEmpty(sortOrder)? "species_desc": "";
```

2023-12-04 23:37 UTC, reidst requested changes

2023-12-04 23:37 UTC, reidst commented on Pages/Search/Index.cshtml.cs
> +            GenusSort = String.IsNullOrEmpty(sortOrder)? "genus": "genus_desc";
Line 67 sort fix:
```csharp
GenusSort = (String.IsNullOrEmpty(sortOrder) || sortOrder.Equals("genus_desc"))? "genus": "genus_desc";
```

2023-12-05 02:53 UTC, k-atej commented on Pages/Search/Index.cshtml.cs
> +            GenusSort = String.IsNullOrEmpty(sortOrder)? "genus": "genus_desc";
Done!

2023-12-05 06:55 UTC, reidst approved these changes

2023-12-05 06:55 UTC, merged